name: Test SSH Connection to Raspberry Pi

on:
  workflow_dispatch:  # Tu peux le déclencher manuellement depuis GitHub

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH test to Raspberry Pi
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.RPI_HOST }}
          port: ${{ secrets.RPI_PORT }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Connexion réussie !"
            uname -a
            uptime
